"""Superhero names for demo trading account generation."""

SUPERHERO_NAMES = [
    "Spider-Man",
    "Batman",
    "Wonder Woman",
    "Superman",
    "Iron Man",
    "Captain America",
    "Thor",
    "Hulk",
    "Black Widow",
    "Wolverine",
    "Flash",
    "Aquaman",
    "Green Lantern",
    "Black Panther",
    "Doctor Strange",
    "Hawkeye",
    "Ant-Man",
    "Scarlet Witch",
    "Vision",
    "Deadpool",
    "Storm",
    "Cyclops",
    "Jean Grey",
    "Nightcrawler",
    "Rogue",
    "Gambit",
    "Beast",
    "Colossus",
    "Iceman",
    "Angel",
    "Daredevil",
    "Luke Cage",
    "Iron Fist",
    "Jessica Jones",
    "Punisher",
    "Ghost Rider",
    "Silver Surfer",
    "Human Torch",
    "Invisible Woman",
    "Mister Fantastic",
    "Thing",
    "Captain Marvel",
    "Shazam",
    "Green Arrow",
    "Batgirl",
    "Supergirl",
    "Nightwing",
    "Robin",
    "Cyborg",
    "Starfire",
    "Raven",
    "Beast Boy",
    "Martian Manhunter",
    "Hawkgirl",
    "Zatanna",
    "Black Canary",
    "Atom",
    "Firestorm",
    "Blue Beetle",
    "Booster Gold",
    "Plastic Man",
    "Swamp Thing",
    "Constantine",
    "Spawn",
    "Invincible",
    "Omni-Man",
    "Static Shock",
    "Moon Knight",
    "Nova",
    "Quasar",
    "War Machine",
    "Falcon",
    "Winter Soldier",
    "Wasp",
    "She-Hulk",
    "Ms. Marvel",
    "Spider-Woman",
    "Elektra",
    "Blade",
    "Hellboy",
    "Judge Dredd",
    "The Tick",
    "Atom Eve",
    "Starlight",
    "Homelander",
    "A-Train",
    "Kimiko",
    "Hughie",
    "Butcher",
    "Nighthawk",
    "Hyperion",
    "Sentry",
    "Blue Marvel",
    "Spectrum",
    "America Chavez",
    "Kate Bishop",
    "Miles Morales",
    "Silk",
    "Spider-Gwen",
    "Shang-Chi",
]
